platform :ios, '11.0'

target 'NYTMostPopularAPI' do
  use_frameworks!
  pod 'Alamofire', '~> 4.5'
  pod 'AlamofireObjectMapper', '~> 5.0'
  pod 'SVProgressHUD', '~> 2.2.5'
  pod 'PopupDialog', '~> 0.7'
end
